version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: espacopessoal-docs-server
    ports:
      - "6001:6001"
    environment:
      - PORT=6001
      - NODE_ENV=production
      - SERVER_NAME=EspacoPessoal Docs Server
      - MAX_CONNECTIONS=100
      - TIMEOUT=30000
      - CORS_ORIGIN=https://docs.espacopessoal.com
    volumes:
      - ./server/logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Note: In production, client will be deployed to Vercel
  # This is only for local development/testing
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: espacopessoal-docs-client
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_NODE_ENV=development
      - NEXT_PUBLIC_WS_URL=ws://localhost:6001
      - NEXT_PUBLIC_APP_NAME=EspacoPessoal Docs
      - NEXT_PUBLIC_DOCUMENT_NAME=shared-document
      - NEXT_PUBLIC_ENABLE_COLLABORATION=true
    depends_on:
      - server
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   container_name: google-docs-clone-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #     - ./ssl:/etc/nginx/ssl
  #   depends_on:
  #     - client
  #     - server
  #   restart: unless-stopped

volumes:
  server_logs:
    driver: local

networks:
  default:
    name: espacopessoal-docs-network 